cuentoneta/cuentoneta

src/assets/scss/reset.scss
src/assets/scss/theme.scss
src/index.html
src/styles.scss

Adaptación de colores y estilos básicos a partir de la guía de estilos disponible en Figma. Se agregan fuentes, tamaños de letra, colores, espaciados y sombreados.

[#105] - Implementar guía de estilos en SCSS

---

src/app/components/bio-summary-card/bio-summary-card.component.scss
src/app/pages/story/story.component.scss

* Oculta navigation bar para vistas mobile.
* Ajusta tarjeta de bio de autor para vistas mobile.

[#133] Ajustar vista de Story para viewport mobile

---

src/app/components/footer/footer.component.html
src/app/components/footer/footer.component.ts
src/app/components/header/header.component.html
src/app/components/header/header.component.ts
src/app/providers/story.service.ts

* Agrega lectura de navs presentes en header y footer desde un método stub en StoryService.

[#127] Agregar navs para listas activas

---

src/app/components/header/header.component.html
src/app/components/header/header.component.scss
src/app/components/header/header.component.ts
src/assets/scss/theme.scss

Se agrega menú funcional de hamburguesa para navegar entre las vistas de la aplicación.
* Ajustes en responsiveness y estilos.

[#147] - Implementar primera versión de menú para vistas mobile

---

src/app/components/bio-summary-card/bio-summary-card.component.html
src/app/providers/story.service.ts

Soluciona problema donde texto estilizado (con itálicas o negritas) de los summary o bios no era parseado y presenatado correctamente.

[#143] - Agrega parse de textos para summary y bio

---

src/index.html

Se adapta social markup usado para v1, con añadidos de faltantes y comentarios.

[#94] - Agrega social markup vía OpenGraph y Twitter metatags

---

cms/schemas/story.ts
src/app/components/header/header.component.scss

* Se corrige bug donde se muestra menú hamburguesa en vistas md+
* Se simplifica preview para tipo Story, eliminando los campos 'edition' y 'day'.

[#151] - Correcciones en visualización de menúes

---

src/app/components/bio-summary-card/bio-summary-card.component.html
src/app/components/footer/footer.component.html
src/app/components/footer/footer.component.ts
src/app/components/header/header.component.html
src/app/components/story-card/story-card.component.html
src/app/pages/home/home.component.html

* Agrega resoluciones fijas para el fetch de las imágenes almacenadas en Sanity.
* Cambia opciones navegables en footer y header.

[#142] - Agregar resolución en fetch de imágenes

---

src/app/pages/story/story.component.scss

* Ajusta spacing horizontal para vista mobile.
* Simplifica hoja de estilos para StoryComponent.

161 adaptar spacing para vista mobile

---

api/_helpers/environment.ts
src/app/components/story-list-card-deck/story-list-card-deck.component.html

* Corrige acceso a variable de entorno `SANITY_TOKEN` en `environment.ts`.
* Remueve uso de operadores de optional chaining innecesarios.

[HF] Corrección de acceso a variable SANITY_TOKEN en helper de environment

---

.gitignore
api/_helpers/environment.ts
api/content-config.ts
package.json
scripts/set-environment.ts
src/app/app.module.ts
src/app/components/header/header.component.ts
src/app/components/story-list-card-deck/story-list-card-deck.component.html
src/app/components/story-list-card-deck/story-list-card-deck.component.ts
src/app/models/content.model.ts
src/app/pages/home/home.component.html
src/app/pages/home/home.component.ts
src/app/providers/content.service.spec.ts
src/app/providers/content.service.ts
src/app/providers/story.service.ts

* Se carga la configuración de contenido cuando la aplicación se inicializa.
* Se genera un archivo `environment.ts` on-the-fly previo a la ejecución del build de la aplicación o luego de ejecutarse `pnpm install`, según el ambiente de ejecución.
* Se realiza una carga programática de los decks de tarjetas de storylists presentados en la landing page.

[#172] - Configuración de contenido desde variables de entorno

---

package.json
pnpm-lock.yaml
scripts/set-environment.ts
tsconfig.app.json
tsconfig.json

* Cambia modo de escritura de writeFile a `w`, para sobreescribir archivo `environment.ts` de ser necesario.
* Actualiza `require()` a `import` en el script, agregando tipos para `yargs` y `dotenv`.

[HF] - Cambiar modo de writefile en script

---

src/app/components/story-card-skeleton/story-card-skeleton.component.html
src/app/components/story-card-skeleton/story-card-skeleton.component.scss
src/app/components/story-card/story-card.component.html
src/app/components/story-card/story-card.component.scss
src/app/components/story-edition-date-label/story-edition-date-label.component.scss
src/assets/scss/theme.scss

* Define altura mínima para contenido de StoryCardComponent.
* Agrega tratamiento de overflow para títulos de StoryCardComponent.
* Ajusta tamaño de fuente en edition/date label según viewport
* Adapta gap, padding y visibilidad de contenido según viewport.

[#206 - FE] Adaptar altura y estilos de cards en vista storylist

---

package.json
src/app/components/story-list-card-deck/story-list-card-deck.component.html
src/app/components/story-list-card-deck/story-list-card-deck.component.scss
src/app/pages/home/home.component.html
src/app/pages/home/home.component.scss
src/app/pages/home/home.component.ts

Transferido el link de navegación a vista de Storylist desde `StoryListCardDeckComponent` a `HomeComponent`.
Agregado script faltante para build local del proyecto.

[#244] Remover link de ver Storylist en vista de Storylist

---

src/app/components/story-card/story-card.component.html
src/app/components/story-card/story-card.component.ts

Usado join de párrafos en reemplazo del hardcode de los dos primeros párrafos en template.

[#266] - Eliminar hardcode de párrafos renderizados en vista previa

---

src/app/components/story-navigation-bar/story-navigation-bar.component.html
src/app/components/story-navigation-bar/story-navigation-bar.component.ts

* Render condicional de fechas en base a configuración de Storylist.
* Render de skeletons y desactivación de navegación para stories no publicadas.
* Índice de ordenamiento respetando configuración de Publication.

[#256] Mejoras en lista de historias en navbar

---

src/app/components/story-navigation-bar/story-navigation-bar.component.html
src/app/components/story-navigation-bar/story-navigation-bar.component.scss

Agrega routerLink en título de navbar.

[#245] - Agrega navegación a storylist desde navbar

---

src/app/app.component.html
src/app/components/footer/footer.component.html
src/app/components/story-card-skeleton/story-card-skeleton.component.html
src/app/components/story-card/story-card.component.html
src/app/components/story-card/story-card.component.stories.ts
src/app/components/story-list-card-deck/story-list-card-deck.component.html
src/app/components/story-navigation-bar/story-navigation-bar.component.html
src/app/pages/home/home.component.html
src/app/pages/story-list/story-list.component.html
src/app/pages/story/story.component.html
src/index.html

Componentes cambiados a self-closed tags.

[#282] - Componentes cambiados a self-closed tags

---

src/index.html

Cambio en declaración de tag `<cuentoneta-root>` en `index.html`. Este tag no puede ser self-closed.

[#282] - Rollback en modificación de tag cuentoneta-root

---

.github/ISSUE_TEMPLATE/issues.yml

Agregado el issue template al proyecto.
Lo hice un poco más completo de lo que figuraba en la descripción del issue con el fin de que haya la información necesaria a la hora de reportar problemas/fallos. 
Cualquier sugerencia, o cosa que quieran modificar me dicen.

[#306] - Creado issue template

---

src/index.html

Se agregó el atributo preconnect para optimizar la carga de las fonts y se hizo el cambio a la nueva api de google fonts.

[#233] - Performance de las fuentes mejorado

---

.github/ISSUE_TEMPLATE/config.yml

Agregado archivo `config.yml` que faltaba

[#306] - Issue template Modificado

---

project.json
src/styles.scss

* Cambiada configuración de dev server para utilizar Vite.
* Cambio en rutas de imports de styles.

[#211] - Establecer Vite como default para dev server

---

src/assets/scss/theme.scss

Corrige el valor de la variable `$primary-100` por el color correcto que está en el Figma.

[#333] - Fix variable -100

---

src/app/components/footer/footer.component.html

Fix del issue https://github.com/rolivencia/cuentoneta/issues/336

[#336] - Cierre de etiqueta footer

---

src/app/components/footer/footer.component.html

Fix del issue https://github.com/rolivencia/cuentoneta/issues/339 alineando los iconos

[#339] - Alineados iconos de redes verticalmente

---

src/app/app-routing.module.ts
src/app/pages/dmca/dmca.component.html
src/app/pages/dmca/dmca.component.scss
src/app/pages/dmca/dmca.component.spec.ts
src/app/pages/dmca/dmca.component.ts

> # Resumen
> * Crea componente dmca dentro de /pages.
> * Configura ruta con lazy-load para componente (basado en about.component).
> * Configura la vista basado en about.component y tomando el contenido de la branch `release/1.0`.

[#257] - Generar componente dmca

---

src/app/components/header/header.component.html
src/app/components/header/header.component.scss
src/assets/scss/theme.scss

@rolivencia  estos fueron los cambios que me indicaste que realizara
Quedo atento.

[#311] - Se realizan los cambios en theme.scss y en el componente header

---

src/index.html

[#314]-Cambio del atributo lang index.html

---

CONTRIBUTING.md
cms/package.json
cms/pnpm-lock.yaml
cms/sanity.config.ts
package.json

* Agregada cuenta `dev@cuentoneta.ar` para acceso en modo sólo lectura a Sanity Studio.
* Actualización de documentación en `CONTRIBUTING.md`
* Versión cambiada a 2.1.0 en `package.json` para corregir error de ejecución de Sanity Studio.

[#349] Agregar cuenta para Sanity Studio en entorno local

---

ROADMAP.md

* Actualiza hitos pasados y futuros detallados en el roadmap del proyecto, incluyendo contenido, funcionalidades y versiones publicadas.
* Actualizada definición del issue #396, a fin de incluir en próximos releases una actualización del documento ROADMAP.md asociada.

[#375] - Actualiza roadmap de 2023

---

cms/schemas/story.ts
src/api/story.service.ts
src/api/storylist.service.ts
src/app/models/story.model.ts
src/app/pages/story/story.component.html

- Agrega campo badLanguage al schema de story.
- Agrega campo badLanguage al fetch de Story y StoryList.
- Agrega propiedad badLanguage, de tipo boolean y opcional, al modelo StoryBase en story.model.ts.
- Implementa el warning de lenguaje adulto como tag `<p>` dentro de StoryComponent para poder visualizar contenido.

[#208] - Agregar warning de lenguaje adulto

---

README.md

Agregada Sole Sasia a la sección de contribuyentes del proyecto, con link a su Github.

[#414] - Agrega a Sole Sasia al README.md

---

package.json

Agrega nuevo script para build de Storybook

[#234] - Agrega script para build de storybook

---

.github/ISSUE_TEMPLATE/content.yml

Agrega versión inicial de `content.yml` para propuestas de contenido para sumar en la plataforma.

[#372] - Agrega issue template para aportar contenido

---

src/app/components/story-card/story-card.component.html
src/app/components/story-card/story-card.component.scss
src/app/pages/story/story.component.html
src/assets/svg/video.svg

- Modifica márgenes superior e izquierdo para posicionamiento del ícono de video en StoryCard.
- Agrega clases CSS para estilos de íconos de formato de consumo en StoryCard.

[#403] - Modifica márgenes para icono de video en StoryCard

---

src/app/app.config.ts
src/app/pages/home/home.component.scss

- Agregado reset de posición vertical de scroll al navegar hacia vistas Story y Storylist.
- Cambios en espacio por arriba y por debajo de links de navegación hacia la vista de Storylist en home.

[HF] - Arreglos en scroll y posición de links

---

src/app/components/story-card/story-card.component.html
src/app/components/story-card/story-card.component.scss
src/app/components/story-navigation-bar/story-navigation-bar.component.html
src/app/components/story-navigation-bar/story-navigation-bar.component.scss
src/assets/svg/video.svg

* Se agrega la visualización del ícono de video en `StoryNavigationBarComponent ` para aquellas stories que poseen contenido audiovisual.
* Se modificó el uso de *ngIf y *ngFor por la nueva sintaxis de control de flujo utilizando @if, @else y @for.
* Se redimensionó la imagen en formato SVG que se usa como ícono de video.
* Se ajustaron estilos en `StoryCardComponent` para adaptarse al nuevo tamaño del ícono de video.

[#402] Agregar ícono de material audiovisual para stories en Navbar

---

src/app/components/footer/footer.component.html
src/app/components/footer/footer.component.scss

* Se agrega el canal de difusión de Whatsapp de La Cuentoneta en la sección de RRSS del footer
* Se corrige el tamaño de los íconos de RRSS a 20px de alto y ancho

[#501] Agregar link a canal de difusión de Whatsapp

---

src/app/app.component.scss
src/app/components/badge/badge.component.scss
src/app/components/bio-summary-card/bio-summary-card.component.scss
src/app/components/footer/footer.component.scss
src/app/components/header/header.component.scss
src/app/components/share-content/share-content.component.scss
src/app/components/story-card-skeleton/story-card-skeleton.component.scss
src/app/components/story-card/story-card.component.scss
src/app/components/story-edition-date-label/story-edition-date-label.component.scss
src/app/components/story-navigation-bar/story-navigation-bar.component.scss
src/app/components/storylist-card-component/storylist-card.component.scss
src/app/components/storylist-card-deck/storylist-card-deck.component.scss
src/app/directives/tooltip.directive.scss
src/app/pages/about/about.component.scss
src/app/pages/dmca/dmca.component.scss
src/app/pages/home/home.component.scss
src/app/pages/story/story.component.scss
src/app/pages/storylist/storylist.component.scss
src/styles.scss

se cambio el uso de @import por @use en los archivos scss salvo en font.scss debido a que es un import de una fuente.

[#487] - Reemplaza el uso de @import por @use en SCSS

---

src/app/pages/about/about.component.html
src/app/pages/about/about.component.scss
src/app/pages/home/home.component.html
src/app/pages/home/home.component.scss

* Se elimina Hero de landing page
* Ajuste de márgenes verticales en landing page
* Agregado del Hero en `AboutComponent`
* Simplificación de estilos varios usando Tailwind y apply

[#516] Relocalizar Hero

---

src/app/components/bio-summary-card/bio-summary-card.component.html

Se cambiaron los usos de la sintaxis "*ngIf" por "@if".

[#529] - Sintaxis *ngIf cambiada por @if

---

src/app/pages/story/story.component.html

Se cambiaron todos los usos de sintaxis "*ngIf" por la nueva sintaxis "@if".

[#528] - Sintaxis *ngIf cambiada por @if en story.component.html

---

cms/schemas/story.ts
src/app/components/epigraph/epigraph.component.scss
src/app/components/epigraph/epigraph.component.spec.ts
src/app/components/epigraph/epigraph.component.ts
src/app/pages/story/story.component.html
src/app/pages/story/story.component.scss
src/app/pages/story/story.component.ts

* Resuelve problema de responsiveness para el render de los epígrafes de las historias en StoryComponent.
* Introduce nuevo componente `EpigraphComponent` para alojar y renderizar el contenido relacionado a epígrafes.

[#542] Corregir distorsiones de estilo en epígrafes largos

---

src/app/components/share-content/share-content.component.html

Se terminó la migración de los componentes con la sintaxis de ngIf a @if

[#531] - Sintaxis *ngIf cambiada por @if

---

src/api/storylist.service.ts
src/app/components/bio-summary-card/bio-summary-card.component.html
src/app/components/story-card/story-card.component.html
src/app/components/story-navigation-bar/story-navigation-bar.component.html
src/app/components/storylist-card-deck/storylist-card-deck.component.html
src/app/pages/story/story.component.html

Este PR aplica dinámicamente el atributo `lang` en secciones de componentes de la aplicación que se sabe pueden variar de idioma entre las diversas stories y storylists.

[#317] Cambiar dinámicamente atributo lang según idioma de story o storylist al que se accede

---

src/app/components/badge/badge.component.ts
src/app/components/resource/resource.component.ts
src/app/components/space-recording-widget/space-recording-widget.component.scss
src/app/components/storylist-card-component/storylist-card.component.ts
src/app/pages/story/story.component.html

**Cambios realizados:**
1. Resuelve los errores de compilación [NG8107](https://angular.io/extended-diagnostics/NG8107).
2. Se usa la directiva [NgOptimizedImage](https://angular.io/guide/image-directive) para aumentar el rendimiento de la apliicación.
3. Resuelve errores al usar código deprecado de Angular Sass.

[#556] Corregir warnings de compilación

---

CONTRIBUTING.md

1. Se hacen los cambios para escribir correctamente el nombre GitHub.
2. Se hacen los cambios para escribir correctamente el nombre GitHub Issues.
3. Se estructura correctamente el enlace para que redirija correctamente al código de conducta.
4. Soluciona el issue https://github.com/cuentoneta/cuentoneta/issues/617.

[#617] Corrección de typos en CONTRIBUTING.md 

---

src/app/components/bio-summary-card/bio-summary-card.component.html

Este pull request realiza los cambios necesarios para reemplazar el uso de la directiva *ngFor por la nueva directiva @for en el archivo bio-and-summary.component.html. 
Se ha actualizado el código para seguir las nuevas convenciones introducidas en Angular versión 17, lo que incluye el uso de @for en lugar de *ngFor para mejorar el rendimiento y simplificar el código.
- Reemplazo de *ngFor por [@for](https://angular.dev/api/core/@for#mat-tab-content-88-0) en el archivo bio-and-summary.component.html.
- Utilización del parámetro track $index para optimizar el seguimiento de cambios en las iteraciones.
- Cierra el issue #577.

Realiza los cambios necesarios para usar @for en lugar de *ngFor~

---

src/app/pages/story/story.component.html

[#580] Realiza los cambios necesarios para usar @for en lugar de *ngFor

---

src/app/components/share-content/share-content.component.html
src/app/pages/story/story.component.html

[#578] Realiza los cambios necesarios para usar @for en lugar de *ngFor

---

src/app/pages/story/story.component.html
src/app/pages/story/story.component.scss
src/app/pages/storylist/storylist.component.html
src/assets/scss/theme.scss
src/styles.scss
tailwind.config.js

Aproveché para cambiar el media query en el storylist-component ya que no había visto que ya se encontraba el tamaño modificado en la configuración de tailwind 👍

[#607] - Clases de tailwind agregadas al story.component

---

src/app/components/story-navigation-bar/story-navigation-bar.component.html
src/app/components/story-navigation-bar/story-navigation-bar.component.ts
src/app/pages/story/story.component.html
src/app/pages/story/story.component.ts

* Agregar conditional chain en aquellos atributos que deben soportar valores undefined en `StoryComponent`.
* Cambiados inputs de `StoryComponent` y `StoryNavigationBarComponent` para soportar valores undefined.

[#643] Corregir error en StoryComponent cuando el slug o la storylist no están definidos

---

src/app/pages/about/about.component.html
src/app/pages/about/about.component.scss
src/app/pages/about/about.component.ts
src/assets/scss/theme.scss
tailwind.config.js

* Agregado de estilos personalizados para `box-shadow` en `tailwind.config.js`.
* Eliminación de archivo de estilos `about.component.scss`.
* Mueve estilos de clase `.hero` a `theme.scss`.
* Aplica estilos asignados a tag `h3` a nueva clase `.h3` para compatibilidad en `theme.scss`.

[#592] Reemplazo de estilos redundantes por clases de Tailwind en FooterComponent

---

src/index.html

Agrega script de Microsoft Clarity a modo de hotfix

[#688] - Insertar script de Microsoft Clarity

---

.github/workflows/testing.yml
package.json
pnpm-lock.yaml
src/app/components/media-resource/media-resource.component.spec.ts

[#439] - Agrega uso de Github Actions para tests en CI

---

.github/workflows/linting.yml
.github/workflows/testing.yml

- Se actualiza la versión de actions/checkout a 4.1.4
- Se actualiza la versión de anpm/action-setup a 4.0.0
- Se actualiza la versión de actions/setup-node a 4.0.2
- Se usa PNPM 9.1.1
- Se actualiza la versión de Ubuntu a 24.04
Soluciona #727.

[#727] Ajuste de versiones y mejoras a los Actions

---

src/app/directives/meta-tags.directive.ts
src/index.html

- Agregado metatag `description` en `index.html`
- Agregada actualización del metatag en el método `setDescription` de `MetaTagService`.

[#420] - Agregar metatag description

---

src/app/components/storylist-navigation-frame/storylist-navigation-frame.component.ts
src/app/directives/fetch-content.directive.ts
src/app/pages/author/author.component.ts
src/app/pages/home/home.component.ts
src/app/pages/story/story.component.ts
src/app/pages/storylist/storylist.component.ts

- Encapsulado uso de `wrapMacroTaskObservable` en `FetchContentDirective`.
- Adaptados componentes que hacen fetch de contenido para utilizar la nueva definición del método `fetchContent$` en `FetchContentDirective`.

[#783] - Encapsular usos de wrapMacroTaskObservable

---

src/app/components/story-card-skeleton/story-card-skeleton.component.html
src/app/components/story-card-skeleton/story-card-skeleton.component.ts
src/app/pages/author/author-skeleton.component.ts
src/app/pages/author/author.component.ts
src/app/pipes/repeat.pipe.spec.ts
src/app/pipes/repeat.pipe.ts

- Agregado componente de skeleton para AuthorComponent.
- Implementa uso de skeletons en lógica y template de AuthorComponent.
- Agregado pipe de repetición para uso en `@for` y `*ngFor`.

[#790] - Crear estructura de skeletons de carga para el contenido de AuthorComponent

---

src/app/components/share-content/share-content.component.ts

Made the unused message optional in the interface and removed it where it is currently not needed.

[#808] - Corrige problemas de linting en ShareContentComponent

---

src/app/components/svg-icon/svg-icon.component.ts

Reemplaza input `svg` basado en decoradores por input signal.

[#823] - Migración de inputs de SvgIconComponent a signals

---

src/app/components/bio-summary-card/bio-summary-card.component.ts

- Migra inputs de `BioSummaryCardComponent` a signals.
- Establece estrategia de detección de cambios del componente en OnPush.

[#817] - Migrar inputs de BioSummaryCardComponent a signals

---

src/app/components/storylist-card-deck/storylist-card-deck.component.html
src/app/components/storylist-card-deck/storylist-card-deck.component.ts

Se hizo el cambio de inputs tradicional a inputs signals con la lógica que tenia para inicializar los valores

[#815] - Migrar inputs a signals en StorylistCardDeckComponent

---

docs/DEVELOPMENT_GUIDE.md

Agrega información sobre herramientas y plugins disponibles para trabajar localmente con Mermaid, detallándolo como la herramienta por defecto para la confección y visualización de diagramas del proyecto.

[#942] - Agrega mermaid a herramientas del proyecto

---

src/api/story/story.service.ts

Agrega tratamiento similar al implementado en #970 pero para la vista de author.

[HF] - Usa función temporal para visualizar cards con X Spaces en vista de autor

---

src/app/components/storylist-card-deck/story-list-card-deck.component.stories.ts
src/app/components/storylist-card-deck/storylist-card-deck.component.html
src/app/components/storylist-card-deck/storylist-card-deck.component.ts
src/app/pages/home/home.component.spec.ts
src/app/pages/storylist/storylist.component.html
src/app/pages/storylist/storylist.component.spec.ts

- Elimina trazas de código referido a grids dinámicas.
- Elimina inputs y lógica redundante y/o en desuso del componente.

[#994] - Simplifica componente StorylistCardDeckComponent

---

src/app/pages/home/home.component.html
src/app/pages/home/home.component.ts

- Limpieza de `home.component.ts` y agregado del procesamiento de los valores de `campaigns` desde la respuesta recibida del endpoint `àpi/landing-page`
- Agregada instancia de `ContentCampaignCarouselComponent` en landing page, incluyendo un skeleton a revisar posteriormente para su implementación final.

[#1045] - Agregar instancia de `ContentCampaignCarouselComponent` en landing page

---

src/app/components/youtube-video-widget/youtube-video-widget.component.spec.ts
src/app/components/youtube-video-widget/youtube-video-widget.component.ts
src/app/mocks/youtube-video.mock.ts

- Migrados tests desde TestBed a Angular Testing Library.
- Agregado mock para tipo de dato `YoutubeVideo`.

920 solucionar problemas en tests de youtubevideowidgetcomponent

---

src/app/pages/home/home.component.html

- Cambios en el texto debajo del carousel de campañas de contenido.
- Modificación de tamaño de headings en texto.

[#913] - Modificar tamaño de tipografías y spacing para texto de landing

---

docs/CONTENT_CAMPAIGNS.md

Se agrega el archivo `docs/CONTENT_CAMPAIGNS.md` para detallar los recursos que se requieren para la creación de una campaña de contenido en La Cuentoneta.

[#913] - Documentación para generación de campañas de contenido

---

src/api/_helpers/clarity-connector.ts
src/api/_helpers/environment.ts
src/api/_utils/clarity.utils.ts
src/app/mocks/clarity.mock.ts

- Agrega conector para obtener datos desde la API de Clarity.
- Agrega token en objeto environment para trabajar con API de Clarity.
- Implementa tipos y funciones de utilidad para trabajar con la respuesta proviniente de la API de Data Export de Microsoft Clarity.
- Agrega mock de respuesta de la API en `clarity.mocks.ts`

[#976] - Implementar conector para API de Microsoft Clarity

---

cms/components/TextAlignComponent.tsx
cms/package.json
cms/pnpm-lock.yaml
cms/schemas/blockContent.ts
cms/tsconfig.json
src/app/components/portable-text-parser/portable-text-parser.component.stories.ts
src/app/directives/portable-text-parser/portable-text-parser.directive.ts

- Agregado tratamiento de atributos de alineación de texto en editor de Portable Text de Sanity Studio
- Agregado de clases según los atributos de Portable Text recibidos en el frontend para renderizar en HTML y CSS la correcta alineación de texto asignada.

[#485] - Agregar alineación de texto para editor y parser de Portable Text

---

docs/qa/TEST_PLAN.md

Se agregó una carpeta con la documentación QA que contiene el archivo TEST_PLAN.
El TEST_PLAN incluye: 
* Objetivos
* Alcance del testing
* Estrategias de testing
* Criterios de aceptación
* Plan de pruebas
* Riesgos
* Documentación

[#1072] - Transcripción del test plan de notion

---

src/app/pages/author/author-skeleton.component.spec.ts

- Implementa smoke test para evaluar el render del componente `AuthorSkeletonComponent`.
- Utiliza Angular Testing Library siguiendo las pautas del _meta-issue_ #1133.
- Cierra el _issue_ #1235.

[#1235] - Agregar tests unitarios para `AuthorSkeletonComponent`

---

src/app/components/share-content/share-content.component.spec.ts
src/app/components/share-content/share-content.component.ts
src/app/components/story-edition-date-label/story-edition-date-label.component.spec.ts
src/app/components/story-edition-date-label/story-edition-date-label.component.ts
src/app/components/storylist-card-deck/storylist-card-deck.component.html
src/app/components/storylist-card-deck/storylist-card-deck.component.spec.ts

Agrega tests unitarios faltantes para `ShareContentComponent`, `StoryEditionDateLabelComponent` y `StoryCardDeckComponent`.

[#1133] - Definir tests unitarios faltantes en Componentes
