- src/app/directives/destroyed.directive.spec.ts
- src/app/directives/destroyed.directive.ts
- src/app/pages/home/home.component.ts
- src/app/pages/story-list/story-list.component.ts
- src/app/pages/story/story.component.ts
* Creada la directiva `destroyedDirective` para desuscribir componentes al momento de `OnDestroy`.
* Implementada la directiva como `hostDirective` en `StoryListComponent`, `HomeComponent` y `StoryComponent`.
> [#144] Aplicar pattern destroyed a componentes

- api/story/latest.js
Se agrega selección desde el párrafo 0 al 2 para el fetch del endpoint latest.
> [#142] - Limita cantidad de párrafos obtenidos en endpoint getLatest

- api/_utils/functions.ts
- api/story/[slug].ts
- api/story/latest.ts
- api/tsconfig.json
* Agrega archivo tsconfig.json mínimo en `/api`
* Se agrega en `true` el flag `allowSyntheticDefaultImports`
* Se mueve el archivo `functions.ts` a la carpeta `/api/utils`
> [#162] - Agregar tsconfig.json para funciones serverless 

- api/_helpers/environment.ts
- api/_helpers/sanity-connector.ts
- api/story/[slug].ts
- api/story/latest.ts
- api/story/original-links.ts
- cms/schemas/story.ts
- cms/scripts/deleteDayPropertyInStory.ts
- src/app/components/story-card/story-card.component.ts
- src/app/components/story-list-card-deck/story-list-card-deck.component.html
- src/app/components/story-list-card-deck/story-list-card-deck.component.ts
- src/app/components/story-navigation-bar/story-navigation-bar.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- src/app/models/story.model.ts
- src/app/models/storylist.model.ts
- src/app/pages/home/home.component.ts
- src/app/pages/story-list/story-list.component.ts
- src/app/pages/story/story.component.ts
* Eliminar campo day de schema Story.
* Eliminar referencias al campo en queries de serverless APIs.
* Adapta `StoryCard` para trabajar con un index en reemplazo del uso de la propiedad `day`.
* Cálculo de # de edición de cada storylist en base a orden de array. 
* Se agrega campo count a modelo Story.
* Se define a los miembros de tipo `Story` y `StoryList` como obligatorios en los componentes de Angular.
* Agrega archivo de migración para ejecutar un `unset` de los documentos Story en CMS.
> [#164] - Eliminar propiedad day de aplicación

- api/story/latest.ts
- cms/package.json
- cms/pnpm-lock.yaml
- cms/schemas/publication.ts
- cms/schemas/schema.ts
- cms/schemas/storylist.ts
- cms/scripts/copyStoriesToPublications.ts
- src/app/components/story-card/story-card.component.html
- src/app/components/story-card/story-card.component.ts
- src/app/components/story-list-card-deck/story-list-card-deck.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- src/app/models/author.model.ts
- src/app/models/content.model.ts
- src/app/models/story.model.ts
- src/app/models/storylist.model.ts
- src/app/pages/home/home.component.html
- src/app/pages/story-list/story-list.component.html
- src/app/providers/story.service.ts
Se agrega el modelo `Publication`, lo cual transforma al modelo `Story` en independiente de la fecha y otros detalles de cuándo se publica la historia y en qué lista. Además, se invierte la dependencia que las `Storylist` tenían sobre `Story`, haciendo ahora que los objetos de tipo `Publication` tengan una relación tanto con una `Story` como con una `Storylist`, permitiendo que atributos relevantes a una publicación de un cuento en un momento y lista dadas sea independiente de los modelos preexistentes.
Se ha migrado la información del gestor de contenido para soportar el nuevo modelo, como así también el endpoint `/latest`, más las vistas y componentes de frontend correspondientes.
* Visualización de fechas en base al campo `displayDates`, ahora incluido en el modelo `Storylist`.
* …
> [#177] Implementacion de entidad Publication

- src/app/pages/story/story.component.html
- src/app/pages/story/story.component.scss
Ajusta altura de barra vertical a la izquierda de los prólogos, según altura del párrafo.
> [#179 - FE] - Ajusta altura de barra vertical en prólogos

- src/app/directives/meta-tags.directive.spec.ts
- src/app/directives/meta-tags.directive.ts
- src/app/pages/story-list/story-list.component.ts
- src/app/pages/story/story.component.ts
Se agregó la directiva `MetaTagsDirective` para actualizar la información de OpenGraph y metadata de SEO según la navegación a vista de Storylist y Story.
> [FE-#196] Actualizar metadata en navegaciones

- scripts/set-environment.ts
- src/app/app.module.ts
- src/app/components/story-list-card-deck/story-list-card-deck.component.html
- src/app/directives/fetch-content.directive.ts
- src/app/pages/home/home.component.ts
- src/app/pages/story-list/story-list.component.ts
- src/app/pages/story/story.component.ts
- src/app/providers/macro-task-wrapper.service.ts
- src/app/providers/story.service.ts
* Agregado de `MacroTaskWrapperService`, un servicio que provee métodos para esperar la ejecución de funciones async en SSR.
* Agregado de fetch discriminado de contenido para las vistas Story y StoryList, en modo CSR y SSR.
* Agregado de prefijo en URL para realizar fetch con URLs absolutas en SSR.
* Agregado de genéricos en `fetchContentWithSourceParams$`.
* Cambio en routerLink de `StoryListCardDeckComponent`.
* Reemplazo de la función `withServerTransition`, deprecada en Angular 16.
> [#10 - FE/SSR] - Generación dinámica de meta tags para vistas Story y StoryList

- api/story/latest.ts
- src/app/components/story-list-card-deck/story-list-card-deck.component.html
- src/app/providers/story.service.ts
* Agregado parámetro `ordering` en método `getLatest` y en el endpoint `/latest` correspondiente.
* Agregada indexación en base a la propiedad `order` de las publicaciones en `StoryListCardDeckComponent`.
> [#248] Agregar parámetro ordering para fetch de `/latest`

- api/story/latest.ts
- cms/schemas/storylist.ts
- src/app/models/storylist.model.ts
* Agrega propiedades `featuredImage` e `images` en modelo y schema de Storylist,
* Retorna propiedades `featuredImage` e `images` al fetch de Storylist
> [#250] - Agregar soporte para imágenes asociadas a storylists

- scripts/set-environment.ts
- src/app/components/story-list-card-deck/story-list-card-deck.component.ts
- src/app/models/content.model.ts
- src/app/pages/home/home.component.html
- src/app/pages/story-list/story-list.component.html
- src/app/pages/story-list/story-list.component.ts
Mejorado el soporte para dibujar skeletons en base a configuración alojada en Sanity, sin necesidad de fetch, generando un objeto de configuración que es asociado a una propiedad en `environment.ts`
* Simplificación del modelo `StorylistDeckConfig`.
* Agregadas modificaciones adicionales en `set-environment.ts` para generar archivo `environment.ts` con los layouts de las vistas previas y las listas completas.
> [#113] - Agregado soporte para configuración de layouts de skeletons

- src/app/pages/story/story.component.html
Cambio en variable que determina el estado de los botones de RRSSS, de `!story` a `fetchContentDirective.isLoading`
> [#274] - Corrige recarga de skeletons en stories RRSS

- cms/schemas/story.ts
- src/app/components/bio-summary-card/bio-summary-card.component.html
- src/app/components/bio-summary-card/bio-summary-card.component.scss
- src/app/components/bio-summary-card/bio-summary-card.component.ts
- src/app/models/story.model.ts
- src/app/pages/story/story.component.html
- tsconfig.json
* Agrega link externo para redirigir a usuario a la ubicación del recurso original del cual tomamos la historia presentada.
* Mejora el diseño responsive para acomodar la información referida a cada autor `BioSummaryCardComponent`.
* Elimina validación `required` para el campo `originalLink` en el schema `Story`.
* Agrega render condicional para links de recurso original y bio completa.
> [#276] Agrega navegación a link original de Story

- src/app/components/share-content/share-content.component.ts
Corregido el encoding de URLs para compartir stories por WhatsApp.
> [#352] - Generación de link para compartir en Whatsapp en vista Story

- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- src/app/components/storylist-card-deck/storylist-card-deck.component.scss
- src/app/components/storylist-card-deck/storylist-card-deck.component.ts
- src/app/pages/home/home.component.html
* Agrega comportamiento habitual de link al hacer hover en el título de un `StorylistCardDeckComponent` cuando el nuevo input `canNavigateToStorylist` está puesto en `true`.
* Implementa `canNavigateToStorylist` en true para las instancias de `StorylistCardDeckComponent` declaradas en `HomeComponent`.
> [#341] Agrega navegación a Storylist al clickear en título de preview

- src/app/components/story-navigation-bar/story-navigation-bar.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.scss
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- src/app/pages/story/story.component.html
- src/app/pages/story/story.component.ts
* Agregados estilos para destacar en navbar la story actualmente en vista
* Limitada la cantidad de stories visibles en la navbar a 10, utilizando como pivot la story actualmente en vista. El método `sliceDisplayedPublications` intenta obtener las cinco historias anteriores y posteriores a la actual seleccionada dentro de la storylist, ajustando los límites en caso de que la story actual sea de las primeras o últimas de la storylist.
> [#288] Mejoras en barra de navegación de storylist

- .eslintrc.json
- scripts/set-environment.ts
* Agregados cambios en script `set-environment.ts` para ajustar apiUrl en el ambiente de staging.
* Agrega impresión en consola de constantes relevantes para facilitar el debugging al hacer deploy.
* Corrección en archivo de configuración de ESLint que generaba problemas al ejecutar la herramienta.
> [#368] Agregar ambiente staging en Vercel

- cms/schemas/story.ts
- src/api/story.service.ts
- src/api/storylist.service.ts
* Agrega campo `videoUrl` al schema `story` en Sanity.
* Agrega propiedad `videoUrl` en los endpoints de la API para
* `story` en `story.service.ts`
* `storylist` en  `story.service.ts`
> [#359] - Agregar propiedad url a schema story

- src/app/models/story.model.ts
- src/app/pages/story/story.component.html
- src/app/pages/story/story.component.scss
- src/app/pages/story/story.component.ts
*  Agrega propiedad `videoUrl`, de tipo `string` y opcional, al modelo `StoryBase` en `story.model.ts`. 
* Implementa el tag `<iframe>` dentro de `StoryComponent` para poder visualizar contenido.
* Agrega clase `video` y define estilos en `story.model.scss` para que el renderizado sea responsive.
> [#359] - Agregar soporte para cuentos en formato video

- src/api/storylist.service.ts
Agrega propiedad videoUrl en endpoint `fetchStorylist` y `fetchStorylistPreview`, incluidos en el archivo `storylist.service.ts`
> [#404] - Agrega propiedad videoUrl en endpoints de storylist service

- src/app/components/story-card/story-card.component.html
- src/app/components/story-edition-date-label/story-edition-date-label.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.html
- src/app/components/storylist-card-deck/storylist-card-deck.component.html
Este PR aborda todos los ítems faltantes de implementación listados en #243:
- Cambio de tags h1 por h2 en títulos de cards.
- Cambio de atributo lang de la página desde `en` a `es`
- Agregado de aria-label para URLs de banderas e imágenes alusivas a autores
- Agregado de `aria-busy=true` al mostrar skeletons
- Cambio de tag `label` a `span` para leyenda y números de historia en `StoryCardComponent`
> [#243] - Mejoras de accesibilidad

- src/app/app.config.ts
- src/app/components/header/header.component.html
- src/assets/scss/transitions.scss
- src/styles.scss
- Se agregó el uso de la ViewTransitionsAPI al router de la aplicación.
- Se generó una transición animada para el contenido de `<main>`, el cual es animado cuando se navega entre las diferentes vistas de la aplicación.
> [#447] Incorporar ViewTransitionsAPI a la aplicación

- cms/schemas/author.ts
- scripts/migrateTextToBlockContent.ts
- src/app/components/bio-summary-card/bio-summary-card.component.html
- src/app/models/author.model.ts
- src/app/models/story.model.ts
- src/app/providers/story.service.ts
- Se agrega soporte para texto en múltiples párrafos en las reseñas de historias y bios de autores.
- Se modifican modelos y schemas para reflejar los tipos correspondientes en las propiedades afectadas. Las propiedades de tipo `string` pasan a ser `string[]` en los modelos y los campos `text` pasan a ser `blockContent` en el schema de Sanity.
- Se agrega script para migración de datos en producción.
> [#430] Soporte para texto de múltiples párrafos en reseñas

- cms/schemas/story.ts
- scripts/adjustReadingTime.ts
* Cambiado el valor de la cantidad de palabras leídas por minuto para generar el valor del campo `approximateReadingTime` de cada story. Pasa de 200 a 180.
* Corrida de script para actualizar los valores de todos los campos `approximateReadingTime` siguiendo la nueva fórmula de cálculo.
> [#175] Recálculo de tiempo de lectura aproximado de las historias

- src/api/story.service.ts
- src/app/models/block-content.model.ts
- src/app/models/story.model.ts
- src/app/providers/story.service.ts
- Agregados modelo para `BlockContent` y sus dependencias, reflejando los tipos de objetos recibidos como respuesta del endpoint `/read`
- Uso de del tipo `BlockContent` en interface `StoryDTO`.
- Uso del tipo `BlockContent` para argumentos de métodos de `StoryService`.
- Corrección en el enviado por duplicado del contenido de la historia
> [#114] Agregar tipo BlockContent de Sanity para propiedades en interface StoryDTO

- src/app/models/author.model.ts
- src/app/models/story.model.ts
- src/app/providers/story.service.ts
- tsconfig.json
- Agregado soporte para reemplazo de ocurrencias de `\n` como delimitador de salto de línea a `<br>` como resultado en HTML.
- Mejoras en modelado de propiedades relacionadas a `Story` y `Author`
- Mejorado tipado en métodos incluidos en `StoryService`
> [#481] Agregar soporte para saltos de línea en parser

- cms/schemas/storylist.ts
Reposiciona ubicación de atributo language en schema storylisty y restringe las posibles opciones seleccionables para los valores del atributo.
> [HF] - Reposiciona ubicación de atributo language en schema storylist

- cms/package.json
- cms/pnpm-lock.yaml
- cms/sanity.config.ts
- cms/schemas/author.ts
- cms/schemas/country.ts
- cms/schemas/schema.ts
- cms/schemas/story.ts
- cms/schemas/storylist.ts
- cms/schemas/tag.ts
- src/api/storylist.service.ts
- src/app/models/storylist.model.ts
- src/app/models/tag.model.ts
- Agrega schema `tag` en Sanity para representar categorías en la aplicación.
- Agrega array de referencias a propiedades `tag` en schema `storylist`.
- Agrega modelo de dominio `Tag`.
- Agrega propiedad `tag` a modelo `Storylist`.
- Agrega campo `tag` a consultas `fetchPreview` y `fetchStorylist` de `/api/storylist.service.ts`.
> [#491] Agregar entidad Tag a schema, modelos de dominio y consultas relacionadas a Storylist

- cms/schemas/landingPage.ts
- cms/schemas/schema.ts
- src/app/components/storylist-card-component/storylist-card.component.scss
- src/app/components/storylist-card-component/storylist-card.component.stories.ts
- src/app/components/storylist-card-component/storylist-card.component.ts
- src/app/models/storylist.model.ts
- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.ts
* Agrega schema `landingPage` a Sanity.
* Agregado de visualización preliminar de storylists en `HomeComponent`.
* Cambios en propiedades de modelos `Storylist` y `StorylistCard`.
* Adapta stories de Storybook para trabajar con inputs de tipo `StorylistCard | null` como input del `StorylistCardComponent`.
> [#96] Agregar nuevo schema para configuración de landing page

- scripts/set-environment.ts
- src/api/content.controller.ts
- src/api/content.service.ts
- src/api/routes.ts
- src/app/components/storylist-card-component/storylist-card.component.ts
- src/app/directives/fetch-content.directive.ts
- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.ts
- src/app/pages/storylist/storylist.component.ts
- src/app/providers/content.service.ts
* Se agregan modificaciones en controllers, services y componentes para soportar la visualización de storylists como previews y como cards en la landing page de la aplicación.
* Se actualiza script `set-environment.ts` para renderizar correctamente los skeletons de las cards.
> [#498] Adaptar contenido en formato Preview y Card para storylists en /home

- src/app/models/block-content.model.ts
- src/app/pages/story/story.component.scss
- src/app/providers/story.service.ts
- src/assets/scss/theme.scss
- src/styles.scss
Se agrega soporte para parsing de links del texto en formato BlockContent para su transformación en tags `<a>` de HTML y asignación de atributos `href` con la URL de navegación.
* Eliminación de selectores de estilos redundantes.
* Agrega color `$interactive-600`.
* Agrega estilos globales para colores de links en `BioSummaryCardComponent`.
> [#507] Agregar manejo de links en texto de BlockContent a parser HTML

- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- src/app/components/storylist-card-deck/storylist-card-deck.component.ts
Hola @rolivencia 👋, pensaba usar el componente StoryCardSkeleton en la [línea 138](https://github.com/cuentoneta/cuentoneta/commit/f1b5866a71ce5bed4290eac9a3defb32261f33b2#diff-0be21753e78a4c854a1e2a0d4a80e8ebe6ff99fc3716cec3cbb85f205436bfc1R138) del template, pero como no tiene un ancho fijo aparece una barra de scroll horizontal a causa de eso y de igual manera la carga es tan rápida que no se nota si se pone el skelleton del la card, pero como dije antes genera un scroll horizontal.
También pensaba agregar los skelletons del template a un componente aparte para mantener el template mas simplificado, pero no se si te parezca la idea o si pueda traer problemas más adelante, así podríamos quitar el ngTemplateOutlet y usar un @if para renderizar uno u otro.
> [#509] - Reemplazar directivas estructurales por sintaxis de control de flujo en storylist-card-deck.component.html

- cms/schemas/story.ts
- src/app/components/badge/badge.component.spec.ts
- src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
- src/app/models/story.model.ts
* El campo `review` del schema `story` es ahora opcional.
* La propiedad `summary` del modelo `StoryDTO` se transforma en opcional.
> [#518] Volver opcional el campo review/summary

- src/app/components/story-edition-date-label/story-edition-date-label.component.html
Se cambiaron los "*ngIf" por la nueva sintaxis "@if" de Angular 17.
> [#533] - Sintaxis *ngIf cambiada por @if

- src/app/pages/home/home.component.html
Corregí la alineación de las tarjetas y títulos en la sección **"¿Buscás otras lecturas?"** para que encajen correctamente.
Antes:
Despues:
El **skeleton** de las tarjetas también se mantiene en la posición y alineación correcta.
> [#558] - Arreglar el responsive en la seccion storylists

- package.json
- pnpm-lock.yaml
- src/app/app.component.ts
**Cambios realizados:**
1. Integrada la herramienta Vercel Speed Insights.
2. Agregado el componente SpeedInsights para iniciar el script de seguimiento de métricas.
3. Actualizado el AppComponent para llamar a injectSpeedInsights en el hook de ciclo de vida ngOnInit.
El propósito de este Pull Request es incorporar Vercel Speed Insights, una herramienta de monitoreo de rendimiento, en nuestra aplicación Angular. Esta integración nos permite hacer un seguimiento y analizar las métricas de rendimiento de la aplicación.
Resuelve el issue #553.
> [#553] Añadida la integración con Vercel Speed Insights

- src/app/components/header/header.component.scss
- src/app/components/space-recording-widget/space-recording-widget.component.scss
- src/app/pages/about/about.component.scss
- src/assets/scss/theme.scss
1. Se ajustan los valores de line-height para que cumpla con los criterios de accesibilidad recomendados por WCAG, tomando como base el documento [text spacing](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html).
2. Soluciona #435.
> [#435] Ajuste de line-height para cumplir con condiciones de accesibilidad

- src/styles.scss
Le hice un pequeño cambio al componente youtube-player, ya que en mobile seguía conservando las medidas que ya tenia el componente por defecto.
> [#630] - Altura cambiada en el componente youtube-player

- src/app/app.component.spec.ts
- src/app/components/storylist-card-component/storylist-card.component.stories.ts
Este issue ya había sido resuelto parcialmente en #497.
Hice un par de cambios para que la imagen que trae de Sanity sea en webp, de igual forma al usar el componene ngsrc se van a aplicar las optimizaciones.
Soluciona #582.
> [#582] - Cambiada la URL de las imágenes de Sanity

- CONTRIBUTING.md
- scripts/remove-all-unpublished-drafts.ts
* Agrega script para eliminar todos los drafts no publicados, en caso de sabotaje de los entornos de Sanity o de polución no intencional de documentos en estado _draft_.
* Agrega aclaración en `CONTRIBUTING.md` acerca de la naturaleza del rol _Contributor_ en Sanity.
> [#634] - Agrega script para eliminar documentos draft

- cms/package.json
- cms/pnpm-lock.yaml
- src/app/components/badge/badge.component.scss
- src/app/components/badge/badge.component.ts
- src/app/components/storylist-card-component/storylist-card.component.ts
- src/app/components/svg-icon/svg-icon.component.ts
- src/assets/scss/theme.scss
- tailwind.config.js
* Transforma estilos de `BadgeComponent` en inline.
* Elimina archivo de estilos dedicados `badge.component.scss`.
* Aplica clase faltante h1 para título en `StorylistCardComponent`.
* Agrega spacing 4.5 a configuración de Tailwind.
* Incluido nuevo componente `SvgIconComponent`, destinado a encapsular íconos en formato SVG.
* Elimina mixins y variables en desuso.
> [#589] Reemplazo de estilos por clases de tailwind en BadgeComponent

- src/app/directives/tooltip.directive.scss
- src/app/directives/tooltip.directive.ts
- src/assets/scss/theme.scss
- src/assets/scss/typography.scss
- src/styles.scss
- tailwind.config.js
* Reemplaza clases de estilos dedicadas por clases de utilidad de Tailwind.
* Agrega spacing 1/2, 5/4 y content-blank en configuración de Tailwind.
* Elimina variables en desuso de `theme.scss`.
* Crea nuevo archivo de estilos globales `typography.scss` para alojar tipografías.
> [#603] Reemplazo de estilos por clases de tailwind en TooltipDirective

- src/app/components/bio-summary-card/bio-summary-card.component.stories.ts
- src/app/components/bio-summary-card/bio-summary-card.component.ts
- src/app/components/portable-text-parser/paragraph-template.directive.spec.ts
- src/app/components/portable-text-parser/paragraph-template.directive.ts
- src/app/components/portable-text-parser/portable-text-parser.component.spec.ts
- src/app/components/portable-text-parser/portable-text-parser.component.stories.ts
- src/app/components/portable-text-parser/portable-text-parser.component.ts
- src/app/components/portable-text-styles-marks-serializer/portable-text-marks-serializer.component.spec.ts
- src/app/components/portable-text-styles-marks-serializer/portable-text-marks-serializer.component.ts
- src/app/components/space-recording-widget/space-recording-widget.stories.ts
- src/app/components/story-card/story-card.component.html
- src/app/components/story-card/story-card.component.stories.ts
- src/app/components/story-card/story-card.component.ts
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- src/app/models/author.model.ts
- src/app/models/story.model.ts
- src/app/models/storylist.model.ts
- src/app/pages/story/story.component.html
- src/app/pages/story/story.component.ts
- src/app/providers/story.service.ts
* Crea nuevo componente `PortableTextParserComponent`, orientado a procesar texto en formato Portable Text y serializarlo a HTML.
* Elimina uso de interface `Paragraph`, reemplazando los métodos de parsing otrora en `StoryService` por el procesamiento del texto de tipo `BlockContent` en el nuevo componente.
* Implementado componente `PortableTextParserComponent` en reemplazo de todos los usos de `innerHTML` en los componentes orientados a mostrar contenido almacenado en Sanity en formato Portable Text (`StoryComponent`, `StoryCardComponent` y `BioSummaryCardComponent`).
* Repara stories de Storybook afectadas por últimos cambios.
> [#588] Implementa componente para parsing de contenido en formato Portable Text

- cms/schemas/author.ts
- package.json
- pnpm-lock.yaml
- scripts/add-slug-field-to-authors.ts
- src/api/_queries/author.query.ts
- src/api/_queries/resources.query.ts
- src/api/_utils/functions.ts
- src/api/author/author.controller.ts
- src/api/author/author.service.ts
- src/api/routes.ts
- src/api/story.controller.ts
- src/api/story.service.ts
- src/api/storylist.service.ts
- src/app/models/author.model.ts
* Agrega campo `slug` al schema `author` y a la interface `AuthorBase`.
* Agrega la devDependency `slugify` para generación programática de slugs.
* Agrega script `add-slug-field-to-authors` para generar slugs de autores en base al campo `name`.
* Agrega ruta `/author` para endpoints relacionados a información de autores.
* Agrega controller y service para manejo de lógica de negocios de entidad `author`.
* Agrega endpoint `/author` para entidades de tipo `story`, orientado a obtener la lista de stories de un autor determinado en base al slug del autor.
* Agrega archivos de subqueries para facilitar escritura de las consultas en formato GROQ hechas a Sanity.
* Agrega función `mapAuthor` para transformar datos crudos obtenidos desde Sanity a objetos con el signature de la interface …
> [#702] Agregar campo slug a schema author y sus modelos relacionados

- cms/schemas/story.ts
- src/api/_utils/functions.ts
- src/api/story.service.ts
- src/api/storylist.service.ts
- src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
- src/app/components/bio-summary-card/bio-summary-card.component.stories.ts
- src/app/components/epigraph/epigraph.component.ts
- src/app/components/story-card/story-card.component.stories.ts
- src/app/components/storylist-card-deck/story-list-card-deck.component.stories.ts
- src/app/models/epigraph.model.ts
- src/app/models/prologue.model.ts
- src/app/models/story.model.ts
- src/app/pages/story/story.component.html
- src/app/providers/story.service.ts
* Reemplaza uso de campo `forewords` en Sanity por `epigraphs`: un tipo de objeto que contiene texto en formato Portable Text para soportar epígrafes de texto enriquecido y multilínea.
* Adapta backend, frontend y modelos de dominio de la aplicación a estos cambios.
> [#552] Agregar soporte para epígrafes multilínea

- project.json
Agrega prerender para rutas `about`, `dmca`, `home`, `story` y `storylist`, mediante el autodescubrimiento de rutas.
> [#279] - Agrega opción de prerender para rutas fijas

- src/api/_queries/storylist.query.ts
- src/api/_utils/functions.ts
- src/api/content.controller.ts
- src/api/content.service.ts
- src/api/storylist.controller.ts
- src/api/storylist.service.ts
- src/app/app.config.ts
- src/app/pages/home/home.component.ts
- src/app/providers/content.service.ts
* Agrega nuevo archivo para almacenar y abstraer queries relacionadas con storylists.
* Relocaliza función `mapStorylist` a `functions.ts`, eliminando además la función redundante `mapStorylistPreview`.
* Implementa endpoint `/content/landing-page`
* Transforma lógica de `ContentService` en frontend para trabajar con una única request hacia el endpoint `/content/landing-page`.
* Mueve tratamiento de params desde `storylist.service.ts` hacia `storylist.controller.ts`, separando correctamente el manejo de la request HTTP de la lógica de negocios implementada por el servicio.
* Elimina uso de token `APP_INITIALIZER` para asignar configuración de contenido previo a inicializar la aplicación.
> [#708] Generar endpoint para obtener storylists del home en una única request

- src/app/app.config.ts
- src/app/components/share-content/share-content.component.html
- src/app/components/share-content/share-content.component.ts
- src/app/components/story-card-skeleton/story-card-skeleton.component.html
- src/app/components/story-card-skeleton/story-card-skeleton.component.ts
- src/app/components/storylist-card-component/storylist-card.component.ts
- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- src/app/components/storylist-card-deck/storylist-card-deck.component.ts
- src/app/pages/story/story.component.html
- src/app/pages/story/story.component.ts
- src/app/providers/theme.service.spec.ts
- src/app/providers/theme.service.ts
- src/index.html
- tailwind.config.ts
- theme.config.ts
* Se remueven todas las definiciones de colores _hardcoded_ del proyecto, desarrollando nueva infraestructura para obtener colores definidos en la configuración de Tailwind.
* Implementado el uso de `ThemeService` a lo largo del proyecto para inyectar programáticamente los colores requeridos.
> [#232] Elimina los colores hardcoded del proyecto

- cms/schemas/story.ts
- src/api/_queries/story.query.ts
- src/api/_queries/storylist.query.ts
- src/api/_utils/functions.ts
- src/api/routes.ts
- src/api/story.service.ts
- src/api/story/interfaces.ts
- src/api/story/story.controller.ts
- src/api/story/story.service.ts
* Agrega atributo `originalPublication`. al schema `story`.
* Agrega abstracciones `storyPreviewCommonFields` y `storyCommonFields` para consultas de stories y storylists.
* Remueve usos de `undefined` en función `mapAuthor()`.
* Reubica `story.service.ts` y `story.controller.ts` a nuevo directorio.
* Implementa controller y service para endpoint `api/story/author`
* Agrega `interfaces.ts` con nuevo signature para función `fetchByAuthorSlug()`.
> [#755] Agregar endpoint para obtener lista de story previews de un autor particular

- src/app/components/media-resource-tags/media-resource-tags.component.spec.ts
- src/app/components/media-resource-tags/media-resource-tags.component.ts
- src/app/components/publication-card/publication-card.component.html
- src/app/components/publication-card/publication-card.component.ts
- src/app/components/story-navigation-bar/story-navigation-bar.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- Agregado nuevo componente `MediaResourceTagsComponent`, el cual lista los íconos a visualizar correspondientes a los distintos recursos multimedia adjuntos a una story.
- Agregados usos del componente en reemplazo de los usos de `@switch` duplicados.
> [#724] Crear componente de visualización de íconos de recursos multimedia

- src/app/components/navigable-publication-teaser/navigable-publication-teaser.component.spec.ts
- src/app/components/navigable-publication-teaser/navigable-publication-teaser.component.ts
- src/app/components/publication-card/publication-card.component.html
- src/app/components/publication-card/publication-card.component.ts
- src/app/components/story-navigation-bar/story-navigation-bar.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- src/app/models/landing-page-content.model.ts
- src/app/models/storylist.model.ts
- src/app/providers/content.service.ts
- src/app/providers/storylist.service.ts
- Abstrae ítems de navegación de `StoryNavigationBar` a nuevo componente `NavigablePublicationTeaser`.
- Agrega propiedad `editionLabel` a interface `Publication`.
- Agrega métodos para mappear propiedad editionLabel.
- Abstrae interface `LandingPageContent` a nuevo archivo, agregándole genéricos.
- Agrega uso de campo editionLabel para publication cards y publication teasers.
> [#760] - Abstraer en un componente los ítems navegables de StoryNavigationBar

- src/app/app.routes.ts
- src/app/components/navigable-publication-teaser/navigable-publication-teaser.component.ts
- src/app/components/story-navigation-bar/story-navigation-bar.component.html
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- src/app/components/storylist-navigation-frame/storylist-navigation-frame.component.spec.ts
- src/app/components/storylist-navigation-frame/storylist-navigation-frame.component.ts
- src/app/guards/redirect-params-for-storylist-in-story-route.guard.ts
- src/app/pages/story/story.component.html
- src/app/pages/story/story.component.ts
- Agrega guard para retrocompatibilidad de definiciones previas de ruta `/story`.
- Reorganiza y desacopla código de componente `StoryNavigationBarComponent`, introduciendo una nueva estructura utilizando proyección del componente `StorylistFrameNavigationComponent` mediante ng-content.
- Actualiza definiciones de `routerLink` referidas a `/story` para acondicionarlas a nueva estructura de rutas.
- Desacopla tratamiento de request a `api/story`, ahora la única en `StoryComponent`, y request a `api/storylist` ahora en `StorylistFrameNavigationComponent`.
> [#707] - Refactor de navegación a Stories asociadas a Storylists

- src/app/pages/author/author.component.ts
- src/app/providers/endpoints.ts
- src/app/providers/story.service.ts
- Agrega template a `AuthorComponent` para visualizar perfil de usuario y stories de su autoría.
- Corrige definiciones de endpoints para obtener las stories de un autor en base a su slug.
> [#778] - Crear template para visualizar datos de perfil de autor y stories de su autoría

- src/app/directives/meta-tags.directive.ts
- src/app/pages/about/about.component.ts
- src/app/pages/author/author.component.ts
- src/app/pages/dmca/dmca.component.ts
- src/app/pages/home/home.component.ts
- src/app/pages/story/story.component.ts
- src/app/pages/storylist/storylist.component.ts
- Agregados metatags de Title y Description al acceder a un perfil de autor.
- Correcciones menores en meta tags de los demás componentes navegables.
- Agregado de nueva lógica y métodos para defaults en `MetaTagsDirective`.
> [#786] - Agregar metatags para perfil de autor

- cms/schemas/author.ts
- src/api/_utils/functions.ts
- src/api/story/story.service.ts
- src/app/components/author-navigation-frame/author-navigation-frame.component.ts
- src/app/components/epigraph/epigraph.component.ts
- src/app/components/navigable-publication-teaser/navigable-publication-teaser.component.ts
- src/app/components/navigable-story-teaser/navigable-story-teaser.component.ts
- src/app/components/publication-card/publication-card.component.stories.ts
- src/app/components/publication-card/publication-card.component.ts
- src/app/components/story-card-content/story-card-content.component.ts
- src/app/components/story-card-content/story-card-content.stories.ts
- src/app/components/story-card/story-card.component.ts
- src/app/components/storylist-navigation-frame/storylist-navigation-frame.component.ts
- src/app/models/epigraph.model.ts
- src/app/models/story.model.ts
- src/app/models/storylist.model.ts
- src/app/pages/author/author.component.ts
- src/app/providers/author.service.ts
- src/app/providers/story.service.ts
- src/app/providers/storylist.service.ts
- Renombra tipo `StoryCard` a `StoryPreview`.
- Asigna tipo `StoryBase` a requests que obtienen stories sin información de autores y a componentes que manipulan stories sin información de autores (`AuthorComponent`, `AuthorNavigationFrameComponent`, `NavigableStoryTeaserComponent`).
- Mueve funciones de mappeo para generación de objetos story previews y stories al backend en `functions.ts` desde los métodos de `StoryService`.
- Agrega restricciones para campos en schema `author`.
- Mueve modelo `Epigraph` al archivo `story.model.ts`.
- Elimina método `parseAvatarImageUrl` de asignación de avatar por default en `StoryService`, reemplazándolo en `StoryCardContent` por una propiedad computed.
> [#690] - Simplificar representación en formato card para stories

- src/app/components/footer/footer.component.ts
As the event is not used currently, it has been removed from the function.
> [#804] - Fix linting issue in FooterComponent

- src/app/components/header/header.component.ts
As the event is not used currently, it has been removed from the function and the template.
> [#805] - Resuelve warnings de linting en HeaderComponent

- src/app/components/badge/badge.component.ts
- src/app/components/resource/resource.component.ts
- src/app/directives/tooltip.directive.ts
- Reemplaza `InputSignals` por `WritableSignals` en `tooltip.directive.ts`.
- Modifica `BadgeComponent` y `ResourceComponent` para hacer uso de la nueva API de TooltipDirective.
> [#867] Reemplaza inputs basados en signals en `TooltipDirective` por writable signals

- cms/schemas/tag.ts
- Se hace uso de `defineType` y `defineConfig` para definir el schema `tag`.
- Se corrige definición de preview y función prepare, en base a nueva información de tipado surgida con la redefinición del schema.
> [#802]`- Migrar schema `tag` definido en `cms/schemas/tag.ts`

- cms/schemas/storylist.ts
Se redefinió el schema `storylist` haciendo uso de las funciones `defineField`, `defineType` y `defineArrayMember` para fortalecer el tipado y autocompletado.
> [#801] - Tipar schema storylist definido en `cms/schemas/storylist.ts`

- cms/schemas/resourceType.ts
- cms/schemas/story.ts
Se redefinió el schema `story` haciendo uso de las funciones `defineField`, `defineType` y `defineArrayMember` para fortalecer el tipado y autocompletado.
> [#800] - Tipar schema story definido en `cms/schemas/story.ts`

- .eslintrc.json
- src/app/components/storylist-card-deck/storylist-card-deck.component.ts
- Remoción de todos los usos de operadores de non-null assertion (!) en el archivo `storylist-card-deck.component.ts`
- Eliminado import en desuso.
- Establece nivel de rigurosidad de las reglas `@typescript-eslint/no-non-null-assertion` y `@typescript-eslint/no-unused-vars` en "error" en la configuración de ESLint.
> [#811] - Corregir warnings del archivo `storylist-card-deck.component.ts`

- .eslintrc.json
- e2e/.eslintrc.json
This Pull Request addresses the issue of enforcing the use of the `@typescript-eslint/no-explicit-any` rule in our ESLint configurations. The rule was added to improve code quality by disallowing the use of the `any` type in TypeScript, which can lead to less type safety and potential bugs.
The issue was raised with the following description:
> "Agregar la regla @typescript-eslint/no-explicit-any con un valor de rigurosidad error en el archivo .eslintrc.json"
1. **Root Configuration (`.eslintrc.json` at the root)**
- Added the rule `@typescript-eslint/no-explicit-any` with `"error"` severity to enforce type safety across the main project.
```json
{
"root": true,
"ignorePatterns": ["!**/*"],
"plugins": ["@nx"],
"overrides": [
{
"files": ["*.ts"],
"extends": [
"plugin:@nx/typescript", …
```
> [#888] - Agregar regla `@typescript-eslint/no-explicit-any` a configuración de ESLint

- src/api/_queries/storylist.query.ts
- src/api/_utils/functions.ts
- src/api/content/content.service.ts
- Agrega coma faltante en query de storylist.
- Agrega función para procesar storylists en formato card de forma diferenciada. Remueve procesamiento de imágenes.
> [HOTFIX] - Resolver problemas de despliegue de versión 2.4.3

- src/api/sanity/types.ts
- src/api/story/story.service.ts
Este PR resuelve un problema con la visualización del texto del campo `summary` en el template del componente `BioSummaryCardComponent`. El problema estaba causado por una definición de tipos y un mappeo erróneos de la propiedad en el backend.
> [HF] - Corrige tipo de dato usado para propiedad summary en query y mapping

- package.json
- pnpm-lock.yaml
- src/api/_utils/functions.ts
- src/api/_utils/media-sources.functions.ts
- Actualiza Rettiwt a la última versión.
- Implementa solución temporaria para evitar llamadas async a Rettiwt en el proceso de mappeo de publicaciones de una storylist (a resolver de forma definitiva en #969)
> [HF] - Resolver problema con carga de Spaces de X

- .husky/pre-commit
- .stylelintrc.json
- Actualizado el archivo [.stylelintrc.json](https://github.com/cuentoneta/cuentoneta/blob/develop/.stylelintrc.json) con reglas adicionales.
- Reemplazado el comando npx por pnpm dlx para que sea consistente con el gestor de paquetes que utilizamos en el proyecto.
- Añadida la instrucción `pnpm dlx stylelint "**/*.{css,scss,sass}" --fix` al archivo [pre-commit](https://github.com/cuentoneta/cuentoneta/blob/develop/.husky/pre-commit) para solucionar los errores de estilo.
- Resuelve el _issue_ #1000.
> [#1000] - Añadido hook de pre-commit de stylelint

- cms/schema.json
- cms/schemas/landingPage.ts
- scripts/set-environment.ts
- scripts/set-test-environment.ts
- src/api/content/content.service.ts
- src/api/sanity/generated-schema-types.ts
- src/app/components/header/header.component.ts
- src/app/models/landing-page-content.model.ts
- src/app/pages/home/home.component.ts
- src/app/providers/content.service.ts
Elimina todas las instancias y usos de la propiedad `previews` en el backend, frontend y modelos de dominio de la aplicación.
> [#1006] - Eliminar trazas de la propiedad `previews` de la aplicación

- src/app/components/story-card/story-card.component.spec.ts
> [#950] - Reimplementación de unit tests para StoryCardComponent

- src/app/components/badge/badge.component.spec.ts
- src/app/mocks/tag.mocks.ts
El uso de `componentInputs` ha sido deprecado en favor de `inputs` para asignar las propiedades de los componentes en Angular Testing Library. 
Más información sobre la deprecación de `componentInputs` se puede encontrar en la documentación oficial:  [ componentInputs deprecado](https://testing-library.com/docs/angular-testing-library/api/#componentinputs-deprecated).
> [#922] -  Reimplementación de unit tests para  BadgeComponent

- cms/schemas/contentCampaign.ts
- cms/schemas/landingPage.ts
- cms/schemas/schema.ts
- cms/utils/validations.ts
- Se implementa el schema `contentCampaign` en Sanity, declarando propiedades análogas al modelo de dominio `ContentCampaign`.
- Se agrega la propiedad `campaigns` en el schema `landingPage`, la cual aloja un arreglo de referencias a objetos de schema de tipo `contentCampaign`.
- Se agrega validación genérica `localizedRequire` con mensaje de error en español, la cual debe de usarse en reemplazo de la validación genérica `required`.
> [#1022] -  Implementar schema `contentCampaign` en Sanity

- src/app/models/landing-page-content.model.ts
- src/app/providers/content.service.ts
- Agregado el atributo `campaigns` en el modelo `LandingPageContent` como propiedad obligatoria.
- Actualizada la firma del método `getLandingPageContent` para soportar los cambios de `LandingPageContent`.
> [#1026] - Incluir atributo `campaigns` en modelo de dominio `LandingPageContent`

- src/app/components/author-teaser/author-teaser.component.stories.ts
- src/app/components/author-teaser/author-teaser.component.ts
- src/app/components/bio-summary-card/bio-summary-card.component.ts
- src/app/components/card/card.component.ts
- src/app/components/space-recording-widget/space-recording-widget.stories.ts
- src/app/pages/story/story.component.html
- src/assets/icons/icon-arrow-right.svg
- src/assets/scss/icons.scss
- src/styles.scss
- Se agrega el input `variant` al componente `AuthorTeaserComponent`, a fin de poder mostrar versiones alternativas del componente para su uso en `BioSummaryCardComponent` y `PublicationCardComponent`.
- Actualización de stories de Storybook de `AuthorTeaserComponent` para ilustrar el uso de las dos variants.
- Agregado de ícono de flecha de navegación en nombres de autores navegables, como prototipo de los nuevos diseños de la v3 del proyecto.
- Correcciones en mocks de Storybook con problemas.
- Mejoras en tamaños y rescaling de imágenes usadas en `AuthorTeaserComponent`.
> [#1030] - Implementación de variants en `AuthorTeaserComponent` y reutilización en `BioSummaryCardComponent`

- src/app/components/publication-card/publication-card.component.ts
- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- Reemplaza el input `storylist` de `PublicationCard` por el paso directo de la propiedad `editionLabel` ya procesada como string.
> [#992] - Elimina dependencia de instancia de storylist en PublicationCard

- src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
> [#946] -  Reimplementación de unit tests para BioSummaryCardComponent

- src/app/components/audio-recording-widget/audio-recording-widget.component.spec.ts
- src/app/components/audio-recording-widget/audio-recording-widget.component.ts
- src/app/mocks/audio-recording.mock.ts
- Agrega mock para objeto del tipo `AudioRecording`.
- Migra tests para `AudioRecordingWidgetComponent` desde TestBed a Angular Testing Library.
- Agrega tests relevantes al componente. Se hace uso de `getByTestId`, con el atributo `data-testid` para resolver la ausencia de `roles` asignables a tags de tipo `audio`. Ver caso de [audio](https://www.w3.org/TR/html-aria/#el-audio) en el sitio del WCAG.
> [#919] - Migra tests de `AudioRecordingWidgetComponent ` a Angular Testing Library

- cms/schemas/contentCampaign.ts
- project.json
- src/api/_utils/functions.ts
- src/app/app.config.ts
- src/app/components/content-campaign-carousel/content-campaign-carousel.component.spec.ts
- src/app/components/content-campaign-carousel/content-campaign-carousel.component.stories.ts
- src/app/components/content-campaign-carousel/content-campaign-carousel.component.ts
- src/app/mocks/content-campaign.mock.ts
- src/app/models/content-campaign.model.ts
- src/styles.scss
- Se agregan las propiedades `imageWidth` e `imageHeight` para los contenidos de los distintos viewports de las instancias de `ContentCampaign`.
- Se define la constante `viewportElementSizes` para centrar en un único origen los valores relevantes a las longitudes de cadenas de texto de títulos y subtítulos y los tamaños de imagen de las slides del carousel en cada viewport soportado.
- Se redefine el schema haciendo uso de la constante `viewportElementSizes`, a fin de evitar repetir código para cada viewport soportado.
- Modifica función `mapContentCampaigns` para agregar los tamaños de imagen de las slides en cada viewport soportado, tomando los tamaños desde `viewportElementSizes`.
- Se agregan estilos de `ngx-owl-carousel-o` en `styles.scss`
- Agrega componente …
> [#1040] - Implementar componente `ContentCampaignCarouselComponent`

- src/app/components/epigraph/epigraph.component.spec.ts
- src/app/mocks/epigraph-mock.ts
> [#928] -  Reimplementación de unit tests para `EpigraphComponent`

- src/app/components/portable-text-styles-marks-serializer/portable-text-marks-serializer.component.spec.ts
- src/app/mocks/portable-text-marks-serializer.mock.ts
> [#924] - Reimplementación de unit tests para `PortableTextMarksSerializerComponent`

- src/app/components/content-campaign-carousel/content-campaign-carousel-skeleton.component.ts
- src/app/components/content-campaign-carousel/content-campaign-carousel.component.stories.ts
- src/app/components/content-campaign-carousel/content-campaign-carousel.component.ts
- src/app/components/storylist-card-component/storylist-card-skeleton.component.ts
- src/app/components/storylist-card-component/storylist-card.component.ts
- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.ts
- Agregado de componente `ContentCampaignCarouselSkeletonComponent` para visualizar skeleton del carrusel de campañas de contenido, incluyendo modificación de stories de Storybook para `ContentCampaignCarouselComponent` para visualizar el estado de carga con skeleton.
- Cambios en uso de spacing para `ContentCampaignCarouselSkeletonComponent`, pasando el margin a utilizar como propiedad de la instancia de `NgxOwlCarouselComponent`.
- Agregado componente `StorylistCardSkeletonComponent` para separación de responsabilidades en la visualización del estado de carga de `StorylistCardComponent`
- Agregado uso de `@defer` con la cláusula `when` para simplificar condiciones de visualización de skeleton o instancias cargadas de componentes.
> [#1049] - Agrega componente para skeleton de carrusel de contenido

- project.json
- src/app/app.component.ts
- src/app/components/publication-card/publication-card.component.stories.ts
- src/app/components/storylist-card-component/storylist-card-skeleton.component.ts
- src/app/components/storylist-card-component/storylist-card.component.stories.ts
- src/app/components/storylist-card-component/storylist-card.component.ts
- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- src/app/pages/about/about.component.html
- src/app/pages/author/author-skeleton.component.ts
- src/app/pages/author/author.component.ts
- src/app/pages/home/home.component.html
- src/assets/scss/theme.scss
- tailwind.config.ts
Se actualizan los estilos del componente `StorylistCardComponent`, de acuerdo a la primera versión del diseño del componente en el Figma para la v3 de La Cuentoneta, eliminando la imagen de cabecera en la card y ajustando los estilos de texto.
- Actualiza ancho máximo del viewport `sm` a 768px y el ancho máximo del viewport `md` a 960px en la configuración de Tailwind.
- Ajusta layout de columnas de el deck de story cards en el template de `AuthorComponent`.
- Configura landing page para usar layout de dos columnas a partir del viewport `sm`.
- Agrega uso de `@defer` en `StorylistCardDeck`, a fin de deferir la carga del componente `PublicationCard` hasta tener cargada al menos una publication.
- Agrega clases `h3` faltantes en headings de nivel 3 de la base de código.
Screenshot que …
> [#1051] - Actualizar layout y estilos de StorylistCardComponent

- src/app/components/space-recording-widget/space-recording-widget.component.spec.ts
- src/app/components/space-recording-widget/space-recording-widget.component.ts
- src/app/mocks/space-recording.mock.ts
- Agrega `aria-label` al anchor principal definido en `SpaceRecordingWidgetComponent`.
- Agrega mock para el tipo `SpaceRecording`.
- Define assertions para tests unitarios de `SpaceRecordingWidgetComponent`
- Reemplaza uso de `effect` por una signal `computed` para la propiedad `spaceUrl`
> [#921] - Solucionar problemas en tests de SpaceRecordingWidgetComponent

- package.json
- pnpm-lock.yaml
- src/app/directives/tooltip.directive.spec.ts
> [#945] - Reimplementación de unit tests para `TooltipDirective`

- src/app/components/content-campaign-carousel/content-campaign-carousel.component.ts
- src/app/providers/theme.service.ts
- tailwind.config.ts
- tailwind.screens.ts
- Agregado nuevo archivo `tailwind.screens.ts` para definir los viewports soportados por la plataforma, extrayéndolos para su uso en otras partes de la aplicación por fuera de la configuración de Tailwind.
- Agregado de método getter `viewport` en `ThemeService` para obtener el viewport actual en el que se ejecuta la aplicación.
- Agregado uso de `viewport` en `ContentCampaignComponent`, permitiendo saber el viewport previo al renderizado de las imágenes del carousel, optimizando la carga inicial.
> [#913] - Optimizar carga de imagenes de carousel

- src/app/components/content-campaign-carousel/content-campaign-carousel.component.spec.ts
- src/app/components/content-campaign-carousel/content-campaign-carousel.component.ts
- Agregados tests unitarios para `ContentCampaignCarouselComponent`.
- Eliminada clase redundante y comentario en template de componente.
> [#1063] - Implementar tests unitarios para `ContentCampaignCarouselComponent`

- src/app/components/publication-card/publication-card.component.spec.ts
- src/app/mocks/story.mock.ts
> [#949] - Reimplementación de unit tests para `PublicationCardComponent`

- src/app/components/resource/resource.component.spec.ts
- src/app/mocks/resource.mock.ts
> [#926] - Reimplementación de unit tests para `resourceComponent`

- src/app/pages/home/home.component.ts
Se elimina un condicional que impedía el indexado del contenido de la landing page y su acceso en modo SSR.
> [HF] - Elimina chequeo de PLATFORM_ID para cargar contenido

- src/app/components/navigable-story-teaser/navigable-story-teaser.component.spec.ts
> [#931] - Reimplementación de unit tests para `NavigableStoryTeaserComponent`

- src/app/components/navigable-publication-teaser/navigable-publication-teaser.component.spec.ts
- src/app/mocks/story.mock.ts
> [#930] Reimplementación de unit tests para `NavigablePublicationTeaserComponent`

- package.json
- src/app/components/storylist-card-deck/storylist-card-deck.component.html
- src/app/components/storylist-card-deck/storylist-card-deck.component.ts
- src/app/pages/storylist/storylist.component.html
- src/app/pages/storylist/storylist.component.ts
- Agregados cambios para separar gestión del layout entre `StorylistComponent` y `StorylistCardDeckComponent`, delegando la responsabilidad de visualizar la información e imagen alusiva de la storylist a `StorylistComponent`
- Corrección en script `delete-unused-assets`.
> [#1101] - Actualizar layout de vista /storylist

- cms/package.json
- cms/pnpm-lock.yaml
- cms/set-environment.ts
Pensaba reutilizar código del archivo `set-environment.ts` de la carpeta scripts usando export y imports pero al ejecutar el archivo `set-environment.ts` del cms me daba error por que son dos espacios de trabajo diferentes de TypeScript.
En la nuevas versiones de Node que ya tienen soporte nativo para TypeScript se se podrá reutilizar código:
- https://nodejs.org/en/learn/typescript/run-natively
> [#1098] - Configuracion agregada para la creacion del .env del cms

- src/app/components/author-navigation-frame/author-navigation-frame.component.spec.ts
- Migra tests del archivo `author-navigation-frame.component.spec.ts` a Angular Testing Library.
- Agrega nuevamente smoke test del componente.
- Añade test adicional para comprobar si la información de un StoryTeaser se renderiza correctamente en el componente.
> [#934] - Migra tests unitarios de `AuthorNavigationFrameComponent` a Angular Test Library

- src/app/components/media-resource-tags/media-resource-tags.component.ts
- src/app/pages/storylist/storylist.component.html
- src/app/pages/storylist/storylist.component.ts
Este PR implementa `NgOptimizedImage` en las referencias a imágenes faltantes en el proyecto.
Se modifica el template de `StorylistComponent` para permitir un alto y ancho fijo en las imágenes alusivas de las storylists.
> [#1127] Implementación de NgOptimizedImage en todas las referencias a imágenes

- src/app/components/most-read-stories-card-deck/most-read-stories-card-deck.component.spec.ts
- src/app/components/most-read-stories-card-deck/most-read-stories-card-deck.component.ts
- src/app/pages/home/home.component.html
- src/app/pages/home/home.component.ts
- Agrega componente `MostReadStoriesCardDeckComponent` y lo agrega en `HomeComponent`
- Define alturas fijadas para elementos de `HomeComponent`, evitando rebote en primera carga de la página.
> [#1150] - Agregar componente `MostReadStoriesCardDeckComponent`

- src/app/app.routes.ts
- src/app/pages/about/about.component.spec.ts
- src/app/pages/about/about.component.ts
- src/app/pages/author/author.component.spec.ts
- src/app/pages/author/author.component.ts
- src/app/pages/dmca/dmca.component.spec.ts
- src/app/pages/dmca/dmca.component.ts
- src/app/pages/home/home.component.spec.ts
- src/app/pages/home/home.component.ts
- src/app/pages/story/story.component.spec.ts
- src/app/pages/story/story.component.ts
- src/app/pages/storylist/storylist.component.spec.ts
- src/app/pages/storylist/storylist.component.ts
Cambios en base a #1156 
- Actualiza export de componentes con *default*
- Actualiza import de componentes en `app.routes.ts` con notación reducida en base a la version 15.0 de router en Angular.
> [#1156] - Exportar componentes como default y actualizar notación de rutas

- resources/apidocs/insomnia.json
- src/api/_queries/author.query.ts
- src/api/_utils/functions.ts
- src/api/author/author.controller.ts
- src/api/author/author.service.ts
- src/api/sanity/types.ts
- src/app/app.routes.server.ts
- src/app/app.routes.ts
- src/app/pages/authors/authors.component.ts
- src/app/providers/author.service.ts
Se implementa una primera versión completamente funcional del índice de autores, a fin de entregar esta información a los crawlers de los buscadores.
- Creación de query `authorsQuery` con su correspondiente tipado.
- Implementación del método `getAll` en AuthorService.
- Creación del endpoint `/api/author`.
- Adición de documentación en Insomnia para el endpoint `/api/author`.
- Generalización de la función de mapeo para generar objetos de tipo `AuthorTeaser` a partir de resultados de queries.
- Desarrollo del componente `AuthorsComponent`.
- Configuración del routing para `AuthorsComponent`.
- Agregado del método `getAll` en `AuthorService`.
> [#1175] - Índice de autores V1

- scripts/set-environment.ts
- src/app/components/author-navigation-frame/author-navigation-frame.component.spec.ts
- src/app/components/author-navigation-frame/author-navigation-frame.component.ts
- src/app/components/story-navigation-bar/story-navigation-bar.component.spec.ts
- src/app/components/story-navigation-bar/story-navigation-bar.component.ts
- src/app/components/storylist-navigation-frame/storylist-navigation-frame.component.spec.ts
- src/app/components/storylist-navigation-frame/storylist-navigation-frame.component.ts
- src/app/directives/meta-tags.directive.ts
- src/app/models/navigation-frame.component.ts
- src/app/pages/story/story.component.html
- src/app/pages/story/story.component.ts
- Agregado manejo de URLs canónicas para mejorar SEO, agregando métodos `setCanonicalUrl` y `removeCanonicalUrl` y utilizándolos en `StoryComponent` para actualizar la URL canónica al navegar hacia y desde la vista de lectura de una Story.
- Adaptados componentes `StoryNavigationBarComponent`, `FrameNavigationComponent`, `AuthorNavigationFrameComponent` y `StorylistNavigationFrameComponent` para utilizar inputs en vez de obtener slugs de navegación de manera independiente desde la URL.
> [#1185] - Manejo de URLs canónicas para mejorar SEO

- src/app/components/audio-recording-widget/audio-recording-widget.component.spec.ts
- src/app/components/media-resource/media-resource.component.spec.ts
- src/app/components/space-recording-widget/space-recording-widget.component.spec.ts
- src/app/components/youtube-video-widget/youtube-video-widget.component.spec.ts
- Agrega tests unitarios para `MediaResourceComponent`, haciendo uso de los mocks preexistentes para los diferentes tipos posibles de Media.
- Fortalece los tests unitarios de `AudioRecordingWidgetComponent`, `SpaceRecordingWidgetComponent` y `YoutubeVideoWidgetComponent`, los cuales tenían tests faltantes relativos al chequeo de la descripción al pie de cada widget.
> [#1197] Definir tests unitarios para `MediaResourceComponent`

- eslint.config.js
- src/app/pages/about/about.component.html
Añadir la regla `@angular-eslint/template/prefer-ngsrc` a la configuración de eslint con el objetivo de unificar el formato del proyecto en lo relativo a esta regla de estilo
- Añadir regla `@angular-eslint/template/prefer-ngsrc` a eslint.config,js
- Ejecutar `pnpm lint` para comprobar que se estaba ejecutando
- Modificar `src/app/pages/about/about.component.html` para cumplir la nueva regla
- Fue necesario añadir un `width` y `height`, para lo cual usé los originales de la imagen
> [#1169] Agregar regla eslint `prefer-ngsrc`

- package.json
- pnpm-lock.yaml
- Agrega `ng-icons` a dependencias del proyecto.
- Agrega los paquetes de `ng-icons` para importar íconos de las bibliotecas de FeatherIcons y SimpleIcons.
> [#1237] - Agregar ng-icons a dependencias del proyecto

- package.json
- pnpm-lock.yaml
- Ejecutar `pnpm remove @angular/platform-browser-dynamic`
- Pese a que la dependencia no se estaba usando de forma directa, ejecutar `pnpm run dev`, `pnpm build`, `pnpm run test` y `pnpm run test:e2e` para asegurar que seguía funcionando corretamente
Es posible que, tras el merge y posterior `pnpm install`, sea necesario borrar la carpeta `.angular` para deshacerse de la caché de vite, ya que he tenido algún problema proveniente de vite tras ejecutar el primer comando que se ha resuelto al eliminar la caché.
> [#1206] - Eliminar dependencia @angular/platform-browser-dynamic

- src/app/components/story-card-teaser/story-card-teaser-skeleton.component.ts
- src/app/components/story-card-teaser/story-card-teaser.component.spec.ts
- src/app/components/story-card-teaser/story-card-teaser.component.stories.ts
- src/app/components/story-card-teaser/story-card-teaser.component.ts
- src/app/models/story.model.ts
- src/assets/scss/typography.scss
- tailwind.config.ts
Se implementan cambios para visualizar teasers de stories que incluyen un extracto de texto, con las consiguientes modificaciones orientadas a proveer de un skeleton acorde y ajustar el diseño de todas las variantes implementadas de `StoryCardTeaserComponent` para que coincidan con la especificación de Figma.
- Agregado de interface `StoryTeaserWithAuthor`, el cual representa teasers de stories que incluyen un extracto de texto en los datos.
- Agregada batería de tests unitarios para probar los cambios relacionados a las nuevas variantes de `StoryCardTeaserComponent`.
- Agregados cambios en stories de Storybook para visualizar todas las variantes de `StoryCardTeaserComponent`
- Agregado de variantes de `lineClamp` a safelist de Tailwind, para agregar las clases dinámicamente.
- Agregado …
> [#1275] - Agregar variantes con resumen de texto para componente `StoryCardTeaserComponent`

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/components/author-teaser/author-teaser.component.stories.ts
- src/app/components/bio-summary-card/bio-summary-card.component.stories.ts
- src/app/components/content-campaign-carousel/content-campaign-carousel.component.stories.ts
- src/app/components/footer/footer.component.spec.ts
- src/app/components/header/header.component.spec.ts
- src/app/components/publication-card/publication-card.component.stories.ts
- src/app/components/story-card-content/story-card-content.stories.ts
- src/app/components/story-card-teaser/story-card-teaser.component.stories.ts
- src/app/components/storylist-card-component/storylist-card.component.stories.ts
- src/app/components/storylist-card-deck/story-list-card-deck.component.stories.ts
- src/app/pages/home/home.component.spec.ts
- src/app/pages/storylist/storylist.component.spec.ts
- src/app/providers/analytics/analytics.mock.service.ts
- src/app/providers/analytics/analytics.service.ts
- Reemplaza `RouterTestingModule` por uso de `provideRouter` en stories de Storybook mediante el uso de `applicationConfig`
- Reemplaza `RouterTestingModule` por uso de `provideRouter` en tests unitarios.
- Genera mock explícito para `AnalyticsService`, reemplazando el uso de `provideMock` para esta clase en `AppComponent` por `AnalyticsServiceMock`.
- Elimina imports redundantes en tests de `HeaderComponent` y `AppComponent`.
> [#1283] - Storybook y Jest: Reemplazo de `RouterTestingModule` por `provideRouter`

- playwright.config.ts
- Se comentó la configuración del navegador WebKit en `playwright.config.ts` para desactivar las pruebas en Safari.
- Cierra el _issue_ #1201 .
> [1201] - Desactiva las pruebas de Playwright para Safari/WebKit

- eslint.config.js
Esta regla garantiza que los errores capturados se preserven al relanzarlos usando la propiedad cause, mejorando la trazabilidad y depuración de errores.
> [#1268] - Agrega regla preserve-caught-error a ESLint

- .github/workflows/ci.yml
- Soluciona problema de colisión con cachés de corridas anteriores de CI/CD en PRs abiertas al usar el SHA de la corrida en vez de un hash de los archivos actualizados.
> [#1313] - Corrige problema de caché en CI/CD

- package.json
- pnpm-lock.yaml
Actualiza el compilador de TypeScript a la versión nativa y más rápida [@typescript/native-preview ](https://github.com/microsoft/typescript-go )para mejorar los tiempos de compilación del proyecto.
> [#1256] - Reemplaza TypeScript con TypeScript Native Preview
